---
Title: Chamadas
Weight: 120
---

= Chamadas

O módulo de chamadas no SuiteCRM permite que os usuários agendem e registrem um registro
de chamadas telefônicas de entrada e saída das quais eles podem participar.

== Ações de Chamadas

Você pode acessar as Ações de Chamada no menu suspenso do módulo Chamadas
para baixo ou pela barra lateral. As ações de Chamadas são as seguintes:

* *Log Chamadas* - Um novo formulário é aberto na Visualização de edição para permitir que você
crie um novo registro de Chamadas.
* *Exibir Chamadas* - Redireciona você para a exibição em lista das Chamadas. Isso permite pesquisar e listar registros de Chamadas.
* *Importar Chamadas* - Redireciona você para o Assistente de importação das Chamadas. Para mais informações, veja link:./../../introduction/user-interface/record-management/#_importing_records[Importing Records].

Para visualizar a lista completa de campos disponíveis ao criar uma Chamadas, veja
link:./../../appendix-a/#_calls_field_list[Calls Field List].

== Gerenciamento de Chamadas

* *Classificar:* Para classificar registros neste módulo, clique em qualquer título de coluna
que é classificável. Isso classificará a coluna crescente ou decrescente.
* *Pesquisar:* Para procurar um registro neste módulo, consulte  link:./../../introduction/user-interface/search[Search] neste guia do usuário.
* *Atualização em Massa:* Para atualizar alguns ou todos os registros na Exibição em Lista, use o menu 
Painel de Atualização em Massa, conforme descrito em link:./../../introduction/user-interface/record-management/#_mass_updating_records[Mass Updating Records] neste guia do usuário.
* *Duplicar:* Para duplicar um registro nesse módulo, você pode clicar no botão Duplicar no
Visualização de detalhes e salve o registro duplicado.
* *Mesclar:* Para mesclar registros duplicados, selecione os registros na lista, clique no link Mesclar na lista suspensa de Ações e avance
através do processo de mesclagem. Para obter mais informações sobre mesclagem de duplicatas,
veja link:./../../introduction/user-interface/record-management/#_merging_records[Merging Records] neste guia do usuário.
* *Excluir:* Para excluir um ou vários registros, você pode selecionar vários registros
na exibição em lista e clique em excluir. Você também pode excluir um Registro na
Visualização de detalhes clicando no botão Excluir. Para um guia mais detalhado
para excluir registros, consulte o link:./../../introduction/user-interface/record-management/#_deleting_records[Deleting Records]
neste guia do usuário.
* *Ver Detalhes:* Para visualizar os detalhes de um registro desse módulo, clique no campo com hiperlink na Visualização em Lista. Isso abrirá o registro na exibição de detalhes.
* *Editar:* Para editar os detalhes de um registro desse módulo, clique no ícone Editar na Exibição em lista ou
clique no botão editar na Visualização de Detalhes, faça as alterações necessárias, e clique em Salvar.
* *Importar/Exportar:* Para obter um guia detalhado sobre a importação e exportação de registros para esse módulo, consulte o
link:./../../introduction/user-interface/record-management/#_importing_records[Importing Records] e
link:./../../introduction/user-interface/record-management/#_exporting_records[Exporting Records] neste guia do usuário.
* *Log:* Para rastrear todas as alterações nos campos auditados, no registro desse módulo, você pode clicar no botão Visualizar log de alterações na tela de detalhes do Chamada ou na visualização de Editar.

* *Fechar:* Para fechar uma chamada, clique no ícone 'x' na tela da lista de chamadas. Você pode
Também feche uma chamada clicando no botão Fechar na visualização de detalhes de uma
Chamada. Você também pode clicar no botão Fechar e criar novo. Isso vai
fechar a chamada que você está visualizando e redirecione-o para a Visualização Editar para
criar um novo registro.
* *Reagendar:* Para reagendar uma chamada, você pode clicar no botão Reagendar na
Visualização de detalhes de uma chamada. Para obter um guia detalhado sobre como reagendar chamadas, consulte
a link:./../../advanced-modules/reschedule/[Reschedule] neste guia do usuário.
