---
Title: Documentos
Weight: 170
---

= Documentos

O módulo Documentos pode ser usado como um repositório para as ocorrências do Cliente ou
arquivos internos. Este conteúdo pode ser carregado, revisado e visualizado, 
além de se relacionar com registros individuais no SuiteCRM.

== Ações de Documentos

Você pode acessar as Ações de Documentos no menu suspenso do módulo Documentos
para baixo ou pela barra lateral. As ações de Documentos são as seguintes:

* *Criar Documentos* - Um novo formulário é aberto na Visualização de edição para permitir que você
crie um novo registro de Documentos.
* *Exibir Documentos* - Redireciona você para a exibição em lista dos registros do módulo Documentos. Isso permite pesquisar e listar registros de Documentos.

Para visualizar a lista completa de campos disponíveis ao criar um registro de Documentos, veja link:./../../appendix-a/#_documents_field_list[Documents Field List].

== Gerenciamento de Documentos

* Para visualizar um anexo, clique no link do anexo na Exibição em lista ou
Vista de detalhe do documento. Para atualizar um documento, você pode criar uma
Revisão de documentos.

* *Classificar:* Para classificar registros neste módulo, clique em qualquer título de coluna
que é classificável. Isso classificará a coluna crescente ou decrescente.
* *Pesquisar:* Para procurar um registro neste módulo, consulte  link:./../../introduction/user-interface/search[Search] neste guia do usuário.
* *Atualização em Massa:* Para atualizar alguns ou todos os registros na Exibição em Lista, use o menu 
Painel de Atualização em Massa, conforme descrito em link:./../../introduction/user-interface/record-management/#_mass_updating_records[Mass Updating Records] neste guia do usuário.
* *Duplicar:* Para duplicar um registro nesse módulo, você pode clicar no botão Duplicar no
Visualização de detalhes e salve o registro duplicado.
* *Mesclar:* Para mesclar registros duplicados, selecione os registros na lista, clique no link Mesclar na lista suspensa de Ações e avance
através do processo de mesclagem. Para obter mais informações sobre mesclagem de duplicatas,
veja link:./../../introduction/user-interface/record-management/#_merging_records[Merging Records] neste guia do usuário.
* *Excluir:* Para excluir um ou vários registros, você pode selecionar vários registros
na exibição em lista e clique em excluir. Você também pode excluir um Registro na
Visualização de detalhes clicando no botão Excluir. Para um guia mais detalhado
para excluir registros, consulte o link:./../../introduction/user-interface/record-management/#_deleting_records[Deleting Records]
neste guia do usuário.
* *Ver Detalhes:* Para visualizar os detalhes de um registro desse módulo, clique no campo com hiperlink na Visualização em Lista. Isso abrirá o registro na exibição de detalhes.
* *Editar:* Para editar os detalhes de um registro desse módulo, clique no ícone Editar na Exibição em lista ou
clique no botão editar na Visualização de Detalhes, faça as alterações necessárias, e clique em Salvar.
* *Importar/Exportar:* Para obter um guia detalhado sobre a importação e exportação de registros para esse módulo, consulte o
link:./../../introduction/user-interface/record-management/#_importing_records[Importing Records] e
link:./../../introduction/user-interface/record-management/#_exporting_records[Exporting Records] neste guia do usuário.
* *Log:* Para rastrear todas as alterações nos campos auditados, no registro desse módulo, você pode clicar no botão Visualizar log de alterações na tela de detalhes do contato ou na visualização de Editar.
